# Generated by Django 5.1.4 on 2024-12-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbookentry',
            name='signature_image',
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='signature_base64',
            field=models.TextField(blank=True, help_text='Base64 encoded signature image', null=True),
        ),
    ]
