# Generated by Django 5.1.4 on 2025-01-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='overlay_image',
            field=models.ImageField(blank=True, null=True, upload_to='events'),
        ),
    ]
