# Generated by Django 5.1.4 on 2025-08-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_event_overlay_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='name',
            field=models.CharField(default='anonymous', help_text='Enter your full name', max_length=100, verbose_name='Full Name'),
        ),
    ]
