# Generated by Django 5.1.4 on 2024-12-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_remove_guestbookentry_signature_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestbookentry',
            name='signature_base64',
        ),
        migrations.AddField(
            model_name='guestbookentry',
            name='signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
    ]
